### PR TITLE
Better management structure files

### PR DESCRIPTION
**Pull request by DanYellow**
- Updates example
- Removes useless import of React and Proptypes in src/withTests.js
- Improves url resolving for windows with upath module

I did this update because the storybook-addon-jest works properly only if your unit test files have a specific name, that's mean that if I have the following structure for my React components
MyComponent/
- index.js(x)
- index.story.js
- index.test.js

storybook-addon-jest will always display the same unit test in storybook's panel. I updated the example to prove my point.

### CODE REVIEW

**Comment by renaudtertrais** [comment]
Hi, thanks for your interest.
I saw your PR but I still not get it, so I need to spend more time on it.

**Comment by DanYellow** [comment]
Hi,

Currently the addon works only if your unit test file as a unique name. For example the following structure:
- src/
--- my-component/
------ index.jsx
------ index.test.jsx
--- my-component-2/
------ index.jsx
------ index.test.jsx

If I use the addon with the current version, it will display only my-component/index.test.jsx's unit test even if I select my-component-2/index.jsx in my storybook. My PR allows to put "file path" as argument of withTests, something like withTests('my-component/index').

**Comment by ndelangen** [comment]
Sorry for the late reply, could you remove the package-lock.json? We use yarn over npm. Adding the package-lock.json file adds 15k+ lines of code 😮

**Comment by DanYellow** [comment]
Ok, I'll do that this week.

**Comment by DanYellow** [comment]
Done.

**Comment by ndelangen** [comment]
Cool, I'll check it out asap!

**Comment by ndelangen** [comment]
@DanYellow Sorry for the long wait, I have more time now.

The jest addon has been merged into the monorepo:
https://github.com/storybooks/storybook/tree/master/addons/jest

I'm trying to figure out how to get this merged back in there, but I lack the context of the change on a code level. Do you think you could help me?

**Comment by ndelangen** [comment]
Ok, I think I found the essentials! Could you verify @DanYellow ? 🙇 

https://github.com/storybooks/storybook/pull/3983

**Comment by DanYellow** [comment]
Ok. I will @ndelangen.

**Comment by DanYellow** [comment]
@ndelangen It looks like I cannot verify the PR. I don't see the button.

**Pull request merged**
